### PR TITLE
Resolve circular references created with schema ID

### LINKED ISSUE #92: Expander:  fails with circular ref based on "id"
json-schema semantics with "id" fail to be expanded properly when references based on "id" define cycle.

This is not much of a problem for swagger specs ("id" is not supported), but this affects go-openapi validate, when it comes to run the json-schema test suite. The jsonschema test suite embeds a testcase with such verification (`jsonschema_suite/refRemote.json`).

### PR DESCRIPTION
**Pull request by fredbi**
* fixes #92

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

File: expander_test.go [hunk 1]
```diff
@@ -1759,6 +1748,31 @@ func TestResolveExtraItem(t *testing.T) {
...
+	err := json.Unmarshal([]byte(jazon), sch)
+	require.NoError(t, err)
+
+	require.NotPanics(t, func() {
+		err = ExpandSchemaWithBasePath(sch, nil, &ExpandOptions{})
+		assert.NoError(t, err)
+	})
+
+	fixturePath = "fixtures/more_circulars/with-id.json"
+	jazon = expandThisOrDieTrying(t, fixturePath)
```
Comment (golangcibot) [inline expander_test.go]: ineffectual assignment to `jazon` (from `ineffassign`)

File: expander.go [hunk 2]
```diff
@@ -343,6 +346,16 @@ func expandSchema(target Schema, parentRefs []string, resolver *schemaLoader, ba
 		}
 	}
 
+	for k := range target.Definitions {
+		t, err := expandSchema(target.Definitions[k], parentRefs, resolver, basePath)
+		if resolver.shouldStopOnError(err) {
+			return &target, err
+		}
+		if t != nil {
```
Comment (golangcibot) [inline expander.go]: if statements should only be cuddled with assignments (from `wsl`)

File: expander.go [hunk 3]
```diff
@@ -343,6 +346,16 @@ func expandSchema(target Schema, parentRefs []string, resolver *schemaLoader, ba
 		}
 	}
 
+	for k := range target.Definitions {
+		t, err := expandSchema(target.Definitions[k], parentRefs, resolver, basePath)
```
Comment (golangcibot) [inline expander.go]: shadow: declaration of "t" shadows declaration at line 308 (from `govet`)
