### PR TITLE
Fix `x-order` not working with number value #162

### LINKED ISSUE #162: `x-order` require value of `number` to be in quotes
```
type User struct {
  // User name
  // Extensions:
  // x-order: 0
  Username string json:"username"
  // Password
  // Extensions:
  // x-order: 1
  Password string json:"password"
}

// userInfo request payload
// swagger:response userInfo
type swaggUserInfo struct {
  // in:body
  Body User
}
```
Output without quotes:
```
userInfo:
  properties:
    password:
      type: string
      x-go-name: Password
      x-order: 1
    username:
      type: string
      x-go-name: Username
      x-order: 0
```

```
type User struct {
  // User name
  // Extensions:
  // x-order: "0"
  Username string json:"username"
  // Password
  // Extensions:
  // x-order: "1"
  Password string json:"password"
}

// userInfo request payload
// swagger:response userInfo
type swaggUserInfo struct {
  // in:body
  Body User
}
```
Output with quotes:
```
userInfo:
  properties:
    username:
      type: string
      x-go-name: Username
      x-order: 0
    password:
      type: string
      x-go-name: Password
      x-order: 1
```

### PR DESCRIPTION
**Pull request by ChandanChainani**
Closes #162

### CODE REVIEW

**Review by casualjim — APPROVED** [review]

File: properties.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ func (items OrderSchemaItems) Less(i, j int) (ret bool) {
 					ret = reflect.ValueOf(ii).String() < reflect.ValueOf(ij).String()
 				}
 			}()
```
Comment (sdghchj) [inline properties.go:58]: these lines are no longer useful after this PR.
