### PR TITLE
fixed json unmarshal for BoolOrSchema

### LINKED ISSUE #148: `AdditionalProperties` doesn't differ empty schema or explicit `false`
Per the documentation: https://swagger.io/docs/specification/data-models/dictionaries/. The following two schemas are the same:

**case: empty schema**

```json
{
  "additionalProperties": {}
}
```

**case: true**

```json
{
  "additionalProperties": true
}
```

Also, from JSON Schema: https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties:

> Setting the additionalProperties schema to false means no additional properties will be allowed.

Which means following schema is different than **case: empty schema**:

**case: false**

```json
{
  "additionalProperties": false
}
```

However, both **case: empty schema** and **case: false** are now parsed into the same value:

```shell
~/tmp/swagger via 🐹 v1.16.5 took 6s 
💤 cat a.json
{
    "definitions": {
        "empty": {
            "additionalProperties": {}
        },
        "false": {
            "additionalProperties": false
        }
    }
}


~/tmp/swagger via 🐹 v1.16.5 
💤 swagger expand a.json
{
  "paths": null,
  "definitions": {
    "empty": {
      "additionalProperties": false
    },
    "false": {
      "additionalProperties": false
    }
  }
}
```

### PR DESCRIPTION
**Pull request by fredbi**
According to the json draft 4 (or later) spec, empty schema is equivalent to true.

* checked with the OP's test case (spec expansion)
* added unit test
* fixes #148

### CODE REVIEW

**Comment by fredbi** [comment]
WIP: I am currently testing this branch against go-swagger's full test suite

**Comment by fredbi** [comment]
Seems ok on go-swagger CI.

File: swagger.go [hunk 1]
```diff
@@ -253,15 +253,15 @@ func (s SchemaOrBool) MarshalJSON() ([]byte, error) {
...
+	if len(data) > 0 {
 		if data[0] == '{' {
 			var sch Schema
 			if err := json.Unmarshal(data, &sch); err != nil {
 				return err
 			}
 			nw.Schema = &sch
 		}
-		nw.Allows = !(data[0] == 'f' && data[1] == 'a' && data[2] == 'l' && data[3] == 's' && data[4] == 'e')
+		nw.Allows = !bytes.Equal(data, []byte("false"))
```
Comment (casualjim) [inline swagger.go:264]: this allocates

**Review by casualjim — APPROVED** [review]

**Review by youyuanwu — APPROVED** [review]
