### PR TITLE
Hang when expanding circular $ref

### LINKED ISSUE #74: Why does spec.IsCircular's behavior depend on basePath?
I am wondering why IsCirclar method in the following line skips  the check when basePath is not set?
https://github.com/go-openapi/spec/blob/master/expander.go#L628

```
func isCircular(ref *Ref, basePath string, parentRefs ...string) bool {
	return basePath != "" && swag.ContainsStringsCI(parentRefs, ref.String())
}
```
That means, if I load a swagger file with circular definitions from a file using loads.Spec, as in
```
doc, _ := loads.Spec(filepath)
doc.Expanded()
```
That will work because the filepath will be used as the above basePath in the circular check.

But if I have a swagger file in memory and load it using loads.Analyzed, as in
```
doc, _  := loads.Analyzed(rawspec, "")
doc.Expanded()
```
This will not work as the empty basePath is passed to the above check and the circle will not be detected.

I could avoid this problem by adding the expansion option explicitly as in
```
doc, _  := loads.Analyzed(rawspec, "")
doc.Expanded(&spec.ExpandOptions{RelativeBase: "/inmemory"})
```

But if IsCircular did not omit the check even if basePath is empty, I wouldn't need to pass the expansion option.

Could someone tell me the reason for this basePatch nil check?

regards, aki

### LINKED ISSUE #76: spec ExpandSpec on circular $ref leaves absolute path in new $ref
When running expand on a spec with a circular $ref, the resulting $ref is left with the full absolute path of the file.

Example: https://github.com/go-swagger/go-swagger/fixtures/canary/bitbucket.org/swagger.json

There are two circular $ref in this spec: 
```
#/definitions/repository
#/definitions/base_commit
```

If I use expand fromthe `swagger expand` command, or independently from `go-openapi/analysis/flatten(), the resolved circular $ref leaves the full absolute path of the file, instead of just `#/definitions/...`

In both case, the `RelativeBase` expand option parameter is set to the absolute path of the spec file.

This is annoying when in go-openapi/analysis, we try to sort out $ref's which are plain definitions.

### PR DESCRIPTION
**Pull request by fredbi**
This PR is not fully satisfying in the sense that it does not fix once and for all the
circular ref story. It improves spec expansion which no more hangs on some complex
circular ref patterns. However, it is not able to produce stable expanded schemas when it
used to hang.

All produced expansions are _correct_, but may vary in the way they expand cycles,
when several cycles do collide. Since we walk the spec at random and this spec is mutating
during the expansion process, we stand no chance to come out with a clean resolution
(i.e. resolve shortest cycles first)

What it does:
* Fixes #76 (absolute path left behind in resolved circular $ref)
* Fixes #74 (isCircular no more checks on basePath!="")
* Contributes #75 (hang is solved, but the (always correct) expanded result may differ from one run to another)
* Contributes go-swagger/go-swagger#957 (hang on circular spec)

Even though you chose not to merge this, and maybe rightly so, there are some advances with
this problem, like a minimal reproducible test case.

Cheers,

Fred

### CODE REVIEW

File: expander.go [hunk 1]
```diff
@@ -224,19 +235,23 @@ func init() {
 func defaultSchemaLoader(
 	root interface{},
 	expandOptions *ExpandOptions,
-	cache ResolutionCache) (*schemaLoader, error) {
+	cache ResolutionCache,
+	context *resolverContext) (*schemaLoader, error) {
```
Comment (golangci) [inline expander.go]: defaultSchemaLoader - result 1 (error) is always nil

**Comment by pytlesk4** [comment]
This looks good to me, I am going to check out your changes and test this against some problematic specs we run into at Stoplight.

**Comment by fredbi** [comment]
How about the unstable aspect of this? I mean, if you expand to validate, this is okay (all cycles are expanded in a somewhat correct way), but if you want, say to get documentation, that's no good.

Is that okay with you?

**Comment by pytlesk4** [comment]
For our use case at Stoplight and Prism, that is fine. We are expanding the spec to do contract testing of request/responses. It would take a bigger refactor to make it stable imo, and it is just nice that it doesn't hang anymore.

**Comment by fredbi** [comment]
We have a problem with that one.

When I attempted to integrate with go-swagger, I could see that this breaks validate.

Validate expands JSON-schema meta schema and this is broken.

**Comment by casualjim** [comment]
I reverted this one

File: expander.go [hunk 2]
```diff
@@ -369,6 +378,19 @@ func normalizePaths(refPath, base string) string {
...
+// denormalizePaths returns to simplest notation on file $ref,
+// i.e. strips the absolute path and sets a path relative to the base path.
+//
+// This is currently used when we rewrite ref after a circular ref has been detected
+func denormalizeFileRef(ref *Ref, relativeBase string) *Ref {
+	if ref.String() == "" || ref.IsRoot() || ref.HasFragmentOnly {
+		return ref
+	}
+	// strip relativeBase from URI
+	r, _ := NewRef(strings.TrimPrefix(ref.String(), relativeBase))
```
Comment (pytlesk4) [inline expander.go]: This line is causing the issue in the validation test. It is creating an invalid JSON Ref, if I change it to this:

```
  // strip relativeBase from URI
	relativeBaseURL, _ := url.Parse(relativeBase)
	relativeBaseURL.Fragment = ""
	r, _ := NewRef(strings.TrimPrefix(ref.String(), relativeBaseURL.String()))
```

Then all of the test in the validate package pass except one. It should be really easy to fix, I have to run, but will try to get to it later if someone else hasn't.

**Comment by fredbi** [comment]
I am fixing this

**Comment by fredbi** [comment]
@pytlesk4 . Oh just realized you push a fix yourself. I am trying to test it with complete go-swagger integration then
